services:
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
      # Pasa las variables VITE_* como argumentos al Dockerfile durante la construcción.
      args:
        VITE_NODE_ENV: ${NODE_ENV}
        VITE_API_URL: ${VITE_API_URL}
        VITE_SOCKET_URL: ${VITE_SOCKET_URL}
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_started
    networks:
      - app-network
    restart: unless-stopped # Reinicia Nginx si falla.

  backend:
    build: ./server
    command: npm start
    env_file: ./.env
    environment:
      # DB_HOST se define aquí para sobreescribir cualquier valor del .env
      - DB_HOST=db_mysql
    depends_on:
      db_mysql:
        condition: service_healthy # Espera a que el healthcheck de MySQL pase.
    networks:
      - app-network
    restart: unless-stopped # Reinicia el backend si falla.

  db_mysql:
    image: mysql:8.0
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 20s
      timeout: 10s
      retries: 10
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - app-network
    restart: unless-stopped # Reinicia MySQL si falla.

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8082:80"
    env_file:
      - ./.env
    environment:
      PMA_HOST: db_mysql
    depends_on:
      - db_mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
