services:
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
      # Pasa las variables VITE_* como argumentos al Dockerfile durante la construcción.
      args:
        VITE_NODE_ENV: ${NODE_ENV}
        VITE_API_URL: ${VITE_API_URL}
        VITE_SOCKET_URL: ${VITE_SOCKET_URL}
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_started
    networks:
      - app-network
    restart: unless-stopped # Reinicia Nginx si falla.

  backend:
    build: ./server
    command: npm start
    environment:
      DB_HOST: db_mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      NODE_ENV: ${NODE_ENV}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      db_mysql:
        condition: service_healthy # Espera a que el healthcheck de MySQL pase.
    networks:
      - app-network
    restart: unless-stopped # Reinicia el backend si falla.

  db_mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      # Se usa CMD-SHELL para poder pasar la variable de entorno con la contraseña de root.
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u root -p$${MYSQL_ROOT_PASSWORD}",
        ]
      interval: 20s # Aumentamos el intervalo entre verificaciones.
      timeout: 10s # Aumentamos el tiempo de espera.
      retries: 10 # Aumentamos el número de reintentos.
    networks:
      - app-network
    restart: unless-stopped # Reinicia MySQL si falla.

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8082:80"
    env_file:
      - ./.env
    environment:
      PMA_HOST: db_mysql
    depends_on:
      - db_mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
