name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Asegúrate de que esta versión coincida con la que usas en tu proyecto

      - name: Install Server Dependencies
        run: npm install
        working-directory: ./server

      - name: Run Server Tests (if any)
        run: npm test # Asegúrate de tener scripts de prueba definidos en server/package.json
        working-directory: ./server
        continue-on-error: true

      - name: Install Client Dependencies
        run: npm install
        working-directory: ./client

      - name: Build Client Application
        run: npm run build
        working-directory: ./client

      - name: Run Client Tests (if any)
        run: npm test # Asegúrate de tener scripts de prueba definidos en client/package.json
        working-directory: ./client
        continue-on-error: true

      - name: Build Server Docker Image
        run: docker build -t tr1-server ./server

      - name: Build Client Docker Image
        run: docker build -t tr1-client ./client